### ISSUE TITLE
Building the wasm as module

### ISSUE THREAD

**Issue by boyanio** [oraoto/pib#13]
Hello,

I thinks this project is great! I wanted to tweak PHP for a long time, but couldn't really do it. I have a fun project to compile different languages to wasm and put them together on the same page, I've called it [the Wheel of WebAssembly](https://github.com/boyanio/wasm-wheel).

To use the PHP part, I need to change the way you build the wasm - I need it to be modularized as I have other emscripten-built sources as well. I have done these changes in my [fork](https://github.com/boyanio/pib) and I was wondering it you were interested in pushing them to you as a PR? :-)

Best,
Boyan

**Comment by oraoto** [comment]
Modularization is great and  PR are welcomed.

Sometime ago, I tried to [run PHP in Node.js](https://github.com/oraoto/pib/issues/8) with `-s MODULARIZE=1`, but I didn't manage to run the module in browser.

**Comment by boyanio** [comment]
Fixed by https://github.com/oraoto/pib/pull/14
