### ISSUE TITLE
Composer packages

### ISSUE THREAD

**Issue by ricomonster** [oraoto/pib#22]
Does pib supports implementation of composer packages?

**Comment by oraoto** [comment]
What do you mean by implementation of composer packages?

PIB is just a PHP interpreter running inside a browser. If you want to use compose packages, you can package or load dynamically the entire vendor folder into emscripten filesystem and include `vendor/autoload.php` as usual.

**Comment by ricomonster** [comment]
I assume by you saying including to emscripten filesystem is by using the flag `--preload-file`?

**Comment by oraoto** [comment]
Yeah, `--preload-file` or load the file in JavaScript.

**Comment by ricomonster** [comment]
i have it loaded but after i included `include('vendor/autoload.php');` in the code, the succeeding code below it doesn't seem to run.

**Comment by oraoto** [comment]
What composer packages are you using?

**Comment by filips123** [comment]
@oraoto 

Is it also possible to include files and directories (composer's vendor directory) dynamically after building? Or to dynamically build them?
What do you mean with "load the file in JavaScript"?

Also, is it possible to preload directory (instead of `--preload-file)?
