### ISSUE TITLE
Cannot call pib_eval

### ISSUE THREAD

**Issue by n-fukuju** [oraoto/pib#53]
When using php-web.js generated by the make command, following error occurs.
'Cannot call unknown function pib_eval'.
When I replace files (php-web.*) with in Github Pages (oraoto.github.io/pib), and call to pib_eval succeeds.
Is there a solution ?
![スクリーンショット 2021-07-07 180403](https://user-images.githubusercontent.com/872445/124736282-d0998880-df51-11eb-90b6-a0b7bb308ffd.png)
![スクリーンショット 2021-07-07 162325](https://user-images.githubusercontent.com/872445/124736320-d8592d00-df51-11eb-9cee-023279594d78.png)

**Comment by oraoto** [comment]
`pib_eval` no longer exists, and my GitHub Pages are outdated.

 Please refer to [php-wasm module](https://github.com/oraoto/pib/tree/master/source) and [docs-source](https://github.com/oraoto/pib/tree/master/docs-source) instead.

**Comment by n-fukuju** [comment]
Call to pib_run succeeded by referring to PhpBase.js.
Thank you !:thumbsup:
