### ISSUE TITLE
Examples crash tab on Firefox 90

### ISSUE THREAD

**Issue by guest271314** [oraoto/pib#56]
FYI "Hello, World" and "phpinfo()" examples crash tab on Firefox 90.

**Comment by blackjyn** [comment]
it crash everywhere, and eat all whole RAM

**Comment by oraoto** [comment]
I don't have Firefox 90 right now, but can confirm high memory usage in FF 91.

It's seems the optimizing compiler consumes more than 2GB memory, and isable `javascript.options.wasm_optimizingjit` fix the issue.
