### ISSUE TITLE
How to add a composer package?

### ISSUE THREAD

**Issue by jaedson-barbosa** [oraoto/pib#58]
Hi, beginner here.
Can you tell me if it is possible, through this library, to run a simple script that uses this library: https://github.com/nfephp-org/sped-da ?
The script I need to work is one like this: https://github.com/nfephp-org/sped-da/blob/master/examples/nfe/danfe.php, the only difference is that the $xml will be passed by the application.
So far I have been using a server to do this, but it would be really cool if it worked on the client side, after all performance is not a priority and I just want to cut my costs.

**Comment by Wulfheart** [comment]
@JaedsonBarbosa how did you manage to accomplish it?
