### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by bigwasp** [oraoto/pib#7]
Hi

I tried to build the WASM File with the build.sh
but it ends with

warning: unresolved symbol: getdtablesize
warning: unresolved symbol: getgrnam
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init
Done

but it seems not to work.
I got the menu with the Button LOADING but nothing more happens

**Comment by oraoto** [comment]
You can just ignore `warning: unresolved symbol` as long as you don't trigger calls to these functions.

And how do you open the index.html file? WASM file must be loaded from a http/https server, so a static file server is required, like `php -S 0.0.0.0:3000 -t .`

**Comment by bigwasp** [comment]
Ok, thanks
I tried to open it via firefox index.html
but it works with php -S 0.0.0.0:3000 -t . or an real WebServer
