### ISSUE TITLE
Performance is not good

### ISSUE THREAD

**Issue by hmmhmmhm** [oraoto/pib#9]
![13](https://user-images.githubusercontent.com/38493722/44310710-c5869480-a415-11e8-8cc2-3fd984e06e03.png)
![14](https://user-images.githubusercontent.com/38493722/44310711-c5869480-a415-11e8-8fbb-83f0dabc54e7.png)

It's 10x slower than the normal version.

**Comment by oraoto** [comment]
With the additon of llvm-lto, [Zend/bench.php](https://oraoto.github.io/pib/?code=%253C%253Fphp%250A%250Ainclude%28%2522Zend%252Fbench.php%2522%29%253B%250A) is now about 5x slower than native PHP in Firefox.

And your test script is about 3x slower in the first case and 15x slower in the second case:

[PIB](https://oraoto.github.io/pib/?code=%253C%253Fphp%250A%2524start%2520%253D%2520microtime%28true%29%253B%250A%2524end%2520%253D%25200%253B%250Afor%2520%28%2524i%2520%253D%25200%253B%2520%2524i%2520%253C%25201000000%253B%2520%252B%252B%2524i%29%2520%257B%250A%2520%2520%2520%2520%2524end%2520%253D%2520%2524_SERVER%255B%27REQUEST_TIME%27%255D%253B%250A%257D%250Aprint%28microtime%28true%29%2520-%2520%2524start%2520.%2520%27%2520%2520%252C%2520%2520%27%29%253B%250A%250A%2524start%2520%253D%2520microtime%28true%29%253B%250A%2524end%2520%253D%25200%253B%250Afor%2520%28%2524i%2520%253D%25200%253B%2520%2524i%2520%253C%25201000000%253B%2520%252B%252B%2524i%29%2520%257B%250A%2520%2520%2520%2520%2524end%2520%253D%2520time%28%29%253B%250A%257D%250Aprint%28microtime%28true%29%2520-%2520%2524start%29%253B): `0.078000068664551 , 0.32200002670288`

[3v4l](https://3v4l.org/tiYpJ): `0.030659198760986  ,  0.022921085357666`
